# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: ff2e7b1543bec15b8b62cfe3c3a5df9c8ae72edf80d7418f4d23bc91a820db00

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.generated.core import ExternalRef, Provenance


__all__ = [
    "Event",
    "EventStatus",
    "Task",
    "TaskSpec",
    "TaskStatus",
]

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EventStatus(StrEnum):
    OPEN = "open"
    PLANNED = "planned"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class TaskStatus(StrEnum):
    OPEN = "open"
    PLANNED = "planned"
    DONE = "done"


# ---------------------------------------------------------------------------
# Event
# ---------------------------------------------------------------------------

class Event(TdbDocument):
    type_: Literal["Event"] = Field(alias="@type", default="Event")
    created_at: TdbDateTime
    name: str
    status: EventStatus
    updated_at: TdbDateTime
    anchor_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    description: str | None = None
    end_datetime: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    location: str | None = None
    priority: int | None = None
    provenance: Provenance | None = None
    start_datetime: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# Task
# ---------------------------------------------------------------------------

class Task(TdbDocument):
    type_: Literal["Task"] = Field(alias="@type", default="Task")
    created_at: TdbDateTime
    name: str
    status: TaskStatus
    updated_at: TdbDateTime
    anchor_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    description: str | None = None
    due_date: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    provenance: Provenance | None = None
    required_context: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# TaskSpec
# ---------------------------------------------------------------------------

class TaskSpec(TdbDocument):
    type_: Literal["TaskSpec"] = Field(alias="@type", default="TaskSpec")
    name: str
    description: str | None = None
    estimated_duration: int | None = None
    priority: int | None = None
    required_context: list[str] = Field(default_factory=list)


