# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: a3af75d716f2d5048f4f944f70b0bb665519cd6fedd44159cd96ce916abf7194

from __future__ import annotations

from typing import ClassVar, Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance



__all__ = [
    "Contact",
    "Person",
]

# ---------------------------------------------------------------------------
# Contact — @subdocument
# ---------------------------------------------------------------------------

class Contact(TdbDocument):
    type_: Literal["Contact"] = Field(alias="@type", default="Contact")
    domicile: str | None = None
    email: str | None = None
    phone: str | None = None


# ---------------------------------------------------------------------------
# Person
# ---------------------------------------------------------------------------

class Person(TdbDocument):
    type_: Literal["Person"] = Field(alias="@type", default="Person")
    label_field: ClassVar[str | None] = "name"
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    updated_at: TdbDateTime
    archived_at: TdbDateTime | None = None
    contact: Contact | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)


