# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: ff2e7b1543bec15b8b62cfe3c3a5df9c8ae72edf80d7418f4d23bc91a820db00

from __future__ import annotations

from typing import Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance

# --- forward references for local nested types ---


__all__ = [
    "Contact",
    "Person",
]

# ---------------------------------------------------------------------------
# Contact — @subdocument
# ---------------------------------------------------------------------------

class Contact(TdbDocument):
    type_: Literal["Contact"] = Field(alias="@type", default="Contact")
    domicile: str | None = None
    email: str | None = None
    phone: str | None = None


# ---------------------------------------------------------------------------
# Person
# ---------------------------------------------------------------------------

class Person(TdbDocument):
    type_: Literal["Person"] = Field(alias="@type", default="Person")
    created_at: TdbDateTime
    name: str
    updated_at: TdbDateTime
    contact: Contact | None = None
    contexts: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    provenance: Provenance | None = None


