# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: 7ccb8a3c1d1f58730cb6a8042af8745025519d5bb536a99b976dffae3d9e3c6f

from __future__ import annotations

from enum import StrEnum
from typing import ClassVar, Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance



__all__ = [
    "ConsideredOption",
    "Decision",
    "DecisionStatus",
    "Problem",
    "ProblemStatus",
    "Question",
    "QuestionStatus",
]

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class DecisionStatus(StrEnum):
    DRAFT = "draft"
    PROPOSED = "proposed"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"
    DEPRECATED = "deprecated"


class ProblemStatus(StrEnum):
    OPEN = "open"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    WONT_FIX = "wont_fix"
    REOPENED = "reopened"


class QuestionStatus(StrEnum):
    OPEN = "open"
    ANSWERED = "answered"
    CLOSED = "closed"


# ---------------------------------------------------------------------------
# ConsideredOption — @subdocument
# ---------------------------------------------------------------------------

class ConsideredOption(TdbDocument):
    type_: Literal["ConsideredOption"] = Field(alias="@type", default="ConsideredOption")
    name: str
    cons: list[str] = Field(default_factory=list)
    pros: list[str] = Field(default_factory=list)
    rejection_reason: str | None = None


# ---------------------------------------------------------------------------
# Decision
# ---------------------------------------------------------------------------

class Decision(TdbDocument):
    type_: Literal["Decision"] = Field(alias="@type", default="Decision")
    label_field: ClassVar[str | None] = "title"
    transitions: ClassVar[dict[str, list[str]] | None] = {'draft': ['proposed', 'rejected'], 'proposed': ['accepted', 'rejected', 'draft'], 'accepted': ['superseded', 'deprecated'], 'rejected': ['draft']}
    decision: str
    provenance: Provenance
    status: DecisionStatus
    title: str
    addresses: list[str] = Field(default_factory=list)
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    consequences: str | None = None
    context: list[str] = Field(default_factory=list)
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    options: list[ConsideredOption] = Field(default_factory=list)
    supersedes: str | None = None


# ---------------------------------------------------------------------------
# Problem
# ---------------------------------------------------------------------------

class Problem(TdbDocument):
    type_: Literal["Problem"] = Field(alias="@type", default="Problem")
    label_field: ClassVar[str | None] = "title"
    transitions: ClassVar[dict[str, list[str]] | None] = {'open': ['investigating', 'resolved', 'wont_fix'], 'investigating': ['open', 'resolved', 'wont_fix'], 'resolved': ['reopened'], 'wont_fix': ['reopened'], 'reopened': ['investigating', 'resolved', 'wont_fix']}
    provenance: Provenance
    status: ProblemStatus
    title: str
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    impact: str | None = None
    open_questions: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Question
# ---------------------------------------------------------------------------

class Question(TdbDocument):
    type_: Literal["Question"] = Field(alias="@type", default="Question")
    label_field: ClassVar[str | None] = "question"
    transitions: ClassVar[dict[str, list[str]] | None] = {'open': ['answered', 'closed'], 'answered': ['closed', 'open'], 'closed': ['open']}
    provenance: Provenance
    question: str
    status: QuestionStatus
    aliases: list[str] = Field(default_factory=list)
    answer: str | None = None
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)


