# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: 7ccb8a3c1d1f58730cb6a8042af8745025519d5bb536a99b976dffae3d9e3c6f

from __future__ import annotations

from typing import ClassVar, Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ActionMode, ExternalRef, Provenance



__all__ = [
    "AddressBookGeocoderAction",
    "Affiliation",
    "Contact",
    "Location",
    "Organization",
    "Person",
]

# ---------------------------------------------------------------------------
# AddressBookGeocoderAction
# ---------------------------------------------------------------------------

class AddressBookGeocoderAction(TdbDocument):
    type_: Literal["AddressBookGeocoderAction"] = Field(alias="@type", default="AddressBookGeocoderAction")
    label_field: ClassVar[str | None] = "name"
    enabled: bool
    executor: str
    mode: ActionMode
    name: str
    provenance: Provenance
    trigger: str
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    max_attempts: int | None = None
    params: str | None = None
    retry_backoff: str | None = None
    timeout: str | None = None


# ---------------------------------------------------------------------------
# Affiliation — @subdocument
# ---------------------------------------------------------------------------

class Affiliation(TdbDocument):
    type_: Literal["Affiliation"] = Field(alias="@type", default="Affiliation")
    organization: str
    end_date: TdbDateTime | None = None
    role: str | None = None
    start_date: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# Contact — @subdocument
# ---------------------------------------------------------------------------

class Contact(TdbDocument):
    type_: Literal["Contact"] = Field(alias="@type", default="Contact")
    domicile: str | None = None
    email: str | None = None
    phone: str | None = None


# ---------------------------------------------------------------------------
# Location
# ---------------------------------------------------------------------------

class Location(TdbDocument):
    type_: Literal["Location"] = Field(alias="@type", default="Location")
    label_field: ClassVar[str | None] = "name"
    name: str
    provenance: Provenance
    address: str | None = None
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    coordinates: tuple[float, float] | None = None
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Organization
# ---------------------------------------------------------------------------

class Organization(TdbDocument):
    type_: Literal["Organization"] = Field(alias="@type", default="Organization")
    label_field: ClassVar[str | None] = "name"
    name: str
    provenance: Provenance
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contact: Contact | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    location: str | None = None


# ---------------------------------------------------------------------------
# Person
# ---------------------------------------------------------------------------

class Person(TdbDocument):
    type_: Literal["Person"] = Field(alias="@type", default="Person")
    label_field: ClassVar[str | None] = "name"
    name: str
    provenance: Provenance
    affiliations: list[Affiliation] = Field(default_factory=list)
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contact: Contact | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)


