# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: 1266ac6a4dde535b9294ac954186d909390a2b5cdc9f822d5272f539f0508a62

from __future__ import annotations

from enum import StrEnum
from typing import ClassVar, Literal

from pydantic import Field, model_validator
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance



__all__ = [
    "Activity",
    "ActivitySpec",
    "Event",
    "EventStatus",
    "Routine",
    "RoutineStep",
    "Task",
    "TaskSpec",
    "TaskStatus",
]

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EventStatus(StrEnum):
    OPEN = "open"
    PLANNED = "planned"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class TaskStatus(StrEnum):
    OPEN = "open"
    PLANNED = "planned"
    DONE = "done"


# ---------------------------------------------------------------------------
# Activity
# ---------------------------------------------------------------------------

class Activity(TdbDocument):
    type_: Literal["Activity"] = Field(alias="@type", default="Activity")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "start_datetime"
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    updated_at: TdbDateTime
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    end_datetime: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    routine: str | None = None
    start_datetime: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# ActivitySpec
# ---------------------------------------------------------------------------

class ActivitySpec(TdbDocument):
    type_: Literal["ActivitySpec"] = Field(alias="@type", default="ActivitySpec")
    name: str
    description: str | None = None
    estimated_duration: int | None = None
    priority: int | None = None


# ---------------------------------------------------------------------------
# Event
# ---------------------------------------------------------------------------

class Event(TdbDocument):
    type_: Literal["Event"] = Field(alias="@type", default="Event")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "start_datetime"
    transitions: ClassVar[dict[str, list[str]] | None] = {'open': ['planned', 'closed', 'cancelled'], 'planned': ['open', 'closed', 'cancelled'], 'closed': ['open'], 'cancelled': ['open']}
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    status: EventStatus
    updated_at: TdbDateTime
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    end_datetime: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    location: str | None = None
    priority: int | None = None
    start_datetime: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# Routine
# ---------------------------------------------------------------------------

class Routine(TdbDocument):
    type_: Literal["Routine"] = Field(alias="@type", default="Routine")
    label_field: ClassVar[str | None] = "name"
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    updated_at: TdbDateTime
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    required_context: list[str] = Field(default_factory=list)
    steps: list[RoutineStep] = Field(default_factory=list)
    trigger: str | None = None


# ---------------------------------------------------------------------------
# RoutineStep
# ---------------------------------------------------------------------------

class RoutineStep(TdbDocument):
    type_: Literal["RoutineStep"] = Field(alias="@type", default="RoutineStep")
    label_field: ClassVar[str | None] = "name"
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    updated_at: TdbDateTime
    activity: ActivitySpec | None = None
    archived_at: TdbDateTime | None = None
    cadence_days: int | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    task: TaskSpec | None = None

    @model_validator(mode="after")
    def _oneof_check(self):
        __tracebackhide__ = True
        if ((1 if self.activity is not None else 0) + (1 if self.task is not None else 0)) != 1:
            raise ValueError('Exactly one of ("activity", "task") must be set')
        return self


# ---------------------------------------------------------------------------
# Task
# ---------------------------------------------------------------------------

class Task(TdbDocument):
    type_: Literal["Task"] = Field(alias="@type", default="Task")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "due_date"
    transitions: ClassVar[dict[str, list[str]] | None] = {'open': ['planned', 'done'], 'planned': ['open', 'done'], 'done': ['open']}
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    status: TaskStatus
    updated_at: TdbDateTime
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    due_date: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    required_context: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# TaskSpec
# ---------------------------------------------------------------------------

class TaskSpec(TdbDocument):
    type_: Literal["TaskSpec"] = Field(alias="@type", default="TaskSpec")
    name: str
    description: str | None = None
    estimated_duration: int | None = None
    priority: int | None = None
    required_context: list[str] = Field(default_factory=list)


