# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: 202204db7317a7136268fe2b1b435aa5105a4aee76f52976b689f869eae31666

from __future__ import annotations

from enum import StrEnum
from typing import ClassVar, Literal

from pydantic import Field, model_validator
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance



__all__ = [
    "Activity",
    "ActivitySpec",
    "Area",
    "Event",
    "EventStatus",
    "Goal",
    "GoalStatus",
    "Project",
    "ProjectStatus",
    "Routine",
    "RoutineStep",
    "Task",
    "TaskSpec",
    "TaskStatus",
]

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EventStatus(StrEnum):
    OPEN = "open"
    PLANNED = "planned"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class GoalStatus(StrEnum):
    ACTIVE = "active"
    ACHIEVED = "achieved"
    ABANDONED = "abandoned"


class ProjectStatus(StrEnum):
    ACTIVE = "active"
    ON_HOLD = "on_hold"
    COMPLETED = "completed"


class TaskStatus(StrEnum):
    OPEN = "open"
    PLANNED = "planned"
    DONE = "done"


# ---------------------------------------------------------------------------
# Activity
# ---------------------------------------------------------------------------

class Activity(TdbDocument):
    type_: Literal["Activity"] = Field(alias="@type", default="Activity")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "start_datetime"
    name: str
    provenance: Provenance
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    end_datetime: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    routine: str | None = None
    start_datetime: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# ActivitySpec
# ---------------------------------------------------------------------------

class ActivitySpec(TdbDocument):
    type_: Literal["ActivitySpec"] = Field(alias="@type", default="ActivitySpec")
    name: str
    description: str | None = None
    estimated_duration: int | None = None
    priority: int | None = None


# ---------------------------------------------------------------------------
# Area
# ---------------------------------------------------------------------------

class Area(TdbDocument):
    type_: Literal["Area"] = Field(alias="@type", default="Area")
    label_field: ClassVar[str | None] = "name"
    name: str
    provenance: Provenance
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Event
# ---------------------------------------------------------------------------

class Event(TdbDocument):
    type_: Literal["Event"] = Field(alias="@type", default="Event")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "start_datetime"
    transitions: ClassVar[dict[str, list[str]] | None] = {'open': ['planned', 'closed', 'cancelled'], 'planned': ['open', 'closed', 'cancelled'], 'closed': ['open'], 'cancelled': ['open']}
    name: str
    provenance: Provenance
    status: EventStatus
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    end_datetime: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    location: str | None = None
    priority: int | None = None
    start_datetime: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# Goal
# ---------------------------------------------------------------------------

class Goal(TdbDocument):
    type_: Literal["Goal"] = Field(alias="@type", default="Goal")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "target_date"
    transitions: ClassVar[dict[str, list[str]] | None] = {'active': ['achieved', 'abandoned'], 'abandoned': ['active']}
    name: str
    provenance: Provenance
    status: GoalStatus
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    success_criteria: str | None = None
    target_date: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# Project
# ---------------------------------------------------------------------------

class Project(TdbDocument):
    type_: Literal["Project"] = Field(alias="@type", default="Project")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "target_date"
    transitions: ClassVar[dict[str, list[str]] | None] = {'active': ['on_hold', 'completed'], 'on_hold': ['active'], 'completed': []}
    name: str
    provenance: Provenance
    status: ProjectStatus
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    target_date: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# Routine
# ---------------------------------------------------------------------------

class Routine(TdbDocument):
    type_: Literal["Routine"] = Field(alias="@type", default="Routine")
    label_field: ClassVar[str | None] = "name"
    name: str
    provenance: Provenance
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    required_context: list[str] = Field(default_factory=list)
    steps: list[RoutineStep] = Field(default_factory=list)
    trigger: str | None = None


# ---------------------------------------------------------------------------
# RoutineStep
# ---------------------------------------------------------------------------

class RoutineStep(TdbDocument):
    type_: Literal["RoutineStep"] = Field(alias="@type", default="RoutineStep")
    label_field: ClassVar[str | None] = "name"
    name: str
    provenance: Provenance
    activity: ActivitySpec | None = None
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    cadence_days: int | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    task: TaskSpec | None = None

    @model_validator(mode="after")
    def _oneof_check(self):
        __tracebackhide__ = True
        if ((1 if self.activity is not None else 0) + (1 if self.task is not None else 0)) != 1:
            raise ValueError('Exactly one of ("activity", "task") must be set')
        return self


# ---------------------------------------------------------------------------
# Task
# ---------------------------------------------------------------------------

class Task(TdbDocument):
    type_: Literal["Task"] = Field(alias="@type", default="Task")
    label_field: ClassVar[str | None] = "name"
    anchor_field: ClassVar[str | None] = "due_date"
    transitions: ClassVar[dict[str, list[str]] | None] = {'open': ['planned', 'done'], 'planned': ['open', 'done'], 'done': ['open']}
    name: str
    provenance: Provenance
    status: TaskStatus
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    due_date: TdbDateTime | None = None
    estimated_duration: int | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    required_context: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# TaskSpec
# ---------------------------------------------------------------------------

class TaskSpec(TdbDocument):
    type_: Literal["TaskSpec"] = Field(alias="@type", default="TaskSpec")
    name: str
    description: str | None = None
    estimated_duration: int | None = None
    priority: int | None = None
    required_context: list[str] = Field(default_factory=list)


