# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: a3af75d716f2d5048f4f944f70b0bb665519cd6fedd44159cd96ce916abf7194

from __future__ import annotations

from typing import ClassVar, Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance


__all__ = [
    "Location",
]

# ---------------------------------------------------------------------------
# Location
# ---------------------------------------------------------------------------

class Location(TdbDocument):
    type_: Literal["Location"] = Field(alias="@type", default="Location")
    label_field: ClassVar[str | None] = "name"
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    updated_at: TdbDateTime
    address: str | None = None
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    # coordinates (xdd:coordinate) omitted
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)


