# GENERATED by firnline-schema codegen — do not edit
<<<<<<< HEAD
# Source lock checksum: fe2f8463c4e632a4b39590a4d1c7b85db733316febcfa930affebafaa56544dd
=======
# Source lock checksum: 202204db7317a7136268fe2b1b435aa5105a4aee76f52976b689f869eae31666
>>>>>>> main

from __future__ import annotations

from typing import ClassVar, Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance


__all__ = [
    "Reminder",
]

# ---------------------------------------------------------------------------
# Reminder
# ---------------------------------------------------------------------------

class Reminder(TdbDocument):
    type_: Literal["Reminder"] = Field(alias="@type", default="Reminder")
    label_field: ClassVar[str | None] = "name"
    created_at: TdbDateTime
    name: str
    provenance: Provenance
    updated_at: TdbDateTime
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    description: str | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    refers_to: str | None = None
    trigger: str | None = None


