# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: ff2e7b1543bec15b8b62cfe3c3a5df9c8ae72edf80d7418f4d23bc91a820db00

from __future__ import annotations

from typing import Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance


__all__ = [
    "Reminder",
]

# ---------------------------------------------------------------------------
# Reminder
# ---------------------------------------------------------------------------

class Reminder(TdbDocument):
    type_: Literal["Reminder"] = Field(alias="@type", default="Reminder")
    created_at: TdbDateTime
    name: str
    updated_at: TdbDateTime
    contexts: list[str] = Field(default_factory=list)
    description: str | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    priority: int | None = None
    provenance: Provenance | None = None
    refers_to: str | None = None
    trigger: str | None = None


