# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: 541db45c5e4047b548e48e54c10eb530dda730898853c8f847822a84a0edb3fa

from __future__ import annotations

from enum import StrEnum
from typing import ClassVar, Literal

from pydantic import Field
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance



__all__ = [
    "ConsideredOption",
    "Decision",
    "DecisionStatus",
]

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class DecisionStatus(StrEnum):
    DRAFT = "draft"
    PROPOSED = "proposed"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"
    DEPRECATED = "deprecated"


# ---------------------------------------------------------------------------
# ConsideredOption — @subdocument
# ---------------------------------------------------------------------------

class ConsideredOption(TdbDocument):
    type_: Literal["ConsideredOption"] = Field(alias="@type", default="ConsideredOption")
    name: str
    cons: list[str] = Field(default_factory=list)
    pros: list[str] = Field(default_factory=list)
    rejection_reason: str | None = None


# ---------------------------------------------------------------------------
# Decision
# ---------------------------------------------------------------------------

class Decision(TdbDocument):
    type_: Literal["Decision"] = Field(alias="@type", default="Decision")
    label_field: ClassVar[str | None] = "title"
    transitions: ClassVar[dict[str, list[str]] | None] = {'draft': ['proposed', 'rejected'], 'proposed': ['accepted', 'rejected', 'draft'], 'accepted': ['superseded', 'deprecated'], 'rejected': ['draft']}
    decision: str
    provenance: Provenance
    status: DecisionStatus
    title: str
    aliases: list[str] = Field(default_factory=list)
    archived_at: TdbDateTime | None = None
    consequences: str | None = None
    context: str | None = None
    contexts: list[str] = Field(default_factory=list)
    derived_from: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    options: list[ConsideredOption] = Field(default_factory=list)
    supersedes: str | None = None


