# GENERATED by firnline-schema codegen — do not edit
# Source lock checksum: ff2e7b1543bec15b8b62cfe3c3a5df9c8ae72edf80d7418f4d23bc91a820db00

from __future__ import annotations

from typing import Literal

from pydantic import Field, model_validator
from firnline_core.base import TdbDateTime, TdbDocument
from firnline_core.models import ExternalRef, Provenance
from firnline_ext_planning.models import TaskSpec

# --- forward references for local nested types ---


__all__ = [
    "Activity",
    "ActivitySpec",
    "Routine",
    "RoutineStep",
]

# ---------------------------------------------------------------------------
# Activity
# ---------------------------------------------------------------------------

class Activity(TdbDocument):
    type_: Literal["Activity"] = Field(alias="@type", default="Activity")
    created_at: TdbDateTime
    name: str
    updated_at: TdbDateTime
    anchor_at: TdbDateTime | None = None
    contexts: list[str] = Field(default_factory=list)
    description: str | None = None
    end_datetime: TdbDateTime | None = None
    external_refs: list[ExternalRef] = Field(default_factory=list)
    provenance: Provenance | None = None
    start_datetime: TdbDateTime | None = None


# ---------------------------------------------------------------------------
# ActivitySpec
# ---------------------------------------------------------------------------

class ActivitySpec(TdbDocument):
    type_: Literal["ActivitySpec"] = Field(alias="@type", default="ActivitySpec")
    name: str
    description: str | None = None


# ---------------------------------------------------------------------------
# Routine
# ---------------------------------------------------------------------------

class Routine(TdbDocument):
    type_: Literal["Routine"] = Field(alias="@type", default="Routine")
    created_at: TdbDateTime
    name: str
    updated_at: TdbDateTime
    contexts: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    provenance: Provenance | None = None
    required_context: list[str] = Field(default_factory=list)
    steps: list[RoutineStep] = Field(default_factory=list)
    trigger: str | None = None


# ---------------------------------------------------------------------------
# RoutineStep
# ---------------------------------------------------------------------------

class RoutineStep(TdbDocument):
    type_: Literal["RoutineStep"] = Field(alias="@type", default="RoutineStep")
    created_at: TdbDateTime
    updated_at: TdbDateTime
    activity: ActivitySpec | None = None
    cadence_days: int | None = None
    contexts: list[str] = Field(default_factory=list)
    external_refs: list[ExternalRef] = Field(default_factory=list)
    provenance: Provenance | None = None
    task: TaskSpec | None = None

    @model_validator(mode="after")
    def _oneof_check(self):
        __tracebackhide__ = True
        if ((1 if self.activity is not None else 0) + (1 if self.task is not None else 0)) != 1:
            raise ValueError('Exactly one of ("activity", "task") must be set')
        return self


